spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Products
server:
  port: 8081
application:
  myRetail:
    apiUrl: https://redsky.target.com/v3/pdp/tcin/
    excludes: ?excludes=taxonomy,price,promotion,bulk_ship,rating_and_review_reviews,rating_and_review_statistics,question_answer_statistics&key=candidate

